// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spenny_Wise.WebAPI.Data_Access;

#nullable disable

namespace Spenny_Wise.WebAPI.Migrations
{
    [DbContext(typeof(SpennyContext))]
    [Migration("20240812161354_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.BudgetEntities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.BudgetEntities.BudgetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BudgetCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Housing",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 2,
                            Name = "Food",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 3,
                            Name = "Transportation",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 4,
                            Name = "Debt Payments",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 5,
                            Name = "Saving",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 6,
                            Name = "Health & Wellness",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 7,
                            Name = "Insurance",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 8,
                            Name = "Personal Care",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 9,
                            Name = "Entertainment",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 10,
                            Name = "Education",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 11,
                            Name = "Giving",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pets",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 13,
                            Name = "Miscellaneous",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 14,
                            Name = "Business Expenses",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 15,
                            Name = "Professional Development",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 16,
                            Name = "Streaming Services",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 17,
                            Name = "Personal Development",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 18,
                            Name = "Home Improvement",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 19,
                            Name = "Travel",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        });
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.BudgetEntities.BudgetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaxAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetItems");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.ExpenseEntities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DateOfExpense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.ExpenseEntities.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tithing",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 3,
                            Name = "Transportation",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 4,
                            Name = "Data",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 5,
                            Name = "Snacks",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beverages",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 7,
                            Name = "Restaurants",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 8,
                            Name = "Housing",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dates",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lease Payment",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 11,
                            Name = "Loan Payment",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 12,
                            Name = "Rent",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 13,
                            Name = "Subscriptions",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 14,
                            Name = "Entertainment",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 15,
                            Name = "Miscellaneous",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 16,
                            Name = "Health",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 17,
                            Name = "Deodorant",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 18,
                            Name = "No Idea",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 19,
                            Name = "Birthdays",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 20,
                            Name = "Holidays",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        },
                        new
                        {
                            Id = 21,
                            Name = "Personal Development",
                            UserId = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf")
                        });
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-58b8-c9d0-e1f2a3b4c5d6"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.UserAuth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshTokenExpiration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationTokenExpiration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerifiedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAuthentication");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.UserEntity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb93e0a5-34a7-4a5a-9827-c6825ef6a7cf"),
                            DateCreated = "8/12/2024",
                            Email = "initial@gmail.com",
                            FirstName = "test",
                            LastName = "test",
                            MiddleName = "test",
                            Name = "test test test",
                            PhoneNumber = "1234567"
                        });
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.BudgetEntities.Budget", b =>
                {
                    b.HasOne("Spenny_Wise.WebAPI.Domain.Models.UserEntity.User", null)
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.BudgetEntities.BudgetCategory", b =>
                {
                    b.HasOne("Spenny_Wise.WebAPI.Domain.Models.UserEntity.User", null)
                        .WithMany("BudgetCategories")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.BudgetEntities.BudgetItem", b =>
                {
                    b.HasOne("Spenny_Wise.WebAPI.Domain.Models.BudgetEntities.Budget", null)
                        .WithMany("BudgetItems")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.ExpenseEntities.Expense", b =>
                {
                    b.HasOne("Spenny_Wise.WebAPI.Domain.Models.UserEntity.User", null)
                        .WithMany("Expenses")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.ExpenseEntities.ExpenseCategory", b =>
                {
                    b.HasOne("Spenny_Wise.WebAPI.Domain.Models.UserEntity.User", null)
                        .WithMany("ExpenseCategories")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.UserRole", b =>
                {
                    b.HasOne("Spenny_Wise.WebAPI.Domain.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spenny_Wise.WebAPI.Domain.Models.UserEntity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.BudgetEntities.Budget", b =>
                {
                    b.Navigation("BudgetItems");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Spenny_Wise.WebAPI.Domain.Models.UserEntity.User", b =>
                {
                    b.Navigation("BudgetCategories");

                    b.Navigation("Budgets");

                    b.Navigation("ExpenseCategories");

                    b.Navigation("Expenses");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
